# Site settings
# These are used to personalize your new site.
title: Jacob Nagle # your name here
logo: "/images/unnamed.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Arts in Cybersecurity (class of 2026)
  <br /><br />
  <a href="https://csuniv.joinhandshake.com/profiles/jacobnagle">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/jacob-nagle-0675b52ba/">View My LinkedIn Profile</a>
repository: "jbnagle/jbnagle.github.io"
github_username:  jbnagle # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

